# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: anful
service: serverless-attendance-bot
frameworkVersion: '4'
useDotenv: true
build:
  esbuild:

    bundle: true
    minify: false
    sourcemap:
      type: linked
      # Whether to set the NODE_OPTIONS on functions to enable sourcemaps on Lambda
      setNodeOptions: true
    exclude: ['@sparticuz/chromium', 'aws-sdk']
    target: 'node18'
    define: { 'require.resolve': undefined }
    platform: 'node'
    buildConcurrency: 10
    packages: external

provider:
  name: aws
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - 'secretsmanager:GetSecretValue'
          Resource: 'arn:aws:secretsmanager:${aws:region}:${aws:accountId}:secret:${env:SECRET_NAME}-*'

  stage: ${opt:stage, 'dev'}
  runtime: nodejs18.x
  region: ${opt:region, "ap-northeast-1"}
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
    TARGET_CHANNEL_ID: ${env:TARGET_CHANNEL_ID}
    SECRET_NAME: ${env:SECRET_NAME}
    REGION: ${self:provider.region}
    STAGE: ${self:provider.stage}
  timeout: 30
  memorySize: 2048
  tracing:
    # Can only be true if API Gateway is inside a stack.
    apiGateway: true
    # Can be true (true equals 'Active'), 'Active' or 'PassThrough'
    lambda: true

functions:
  slack:
    handler: src/app.handler
    timeout: 28
    layers:
      - arn:aws:lambda:${aws:region}:764866452798:layer:chrome-aws-lambda:47
    events:
      - httpApi:
          method: POST
          path: /slack/events

  checkPresence:
    handler: src/app.checkPresence
    layers:
      - arn:aws:lambda:${aws:region}:764866452798:layer:chrome-aws-lambda:47
    events:
      - schedule:
          rate: rate(1 minute)
          enabled: true
    # Add any environment variables specific to checkPresence if needed
plugins:
  - serverless-dotenv-plugin
  - serverless-offline

package:
  patterns:
    - '!yarn*'
    - '!.serverless/**'
    - '!.vscode/**'
    - '!.esbuild/**'
    - '!node_modules/**'
    - '!nodemon.json'
    - '!eslintrc.json'
